name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Git User
        run: |
          git config --global user.email "${{ secrets.HEROKU_EMAIL }}"
          git config --global user.name "Farh4nHanz"

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo -e "machine api.heroku.com\n  login ${{ secrets.HEROKU_EMAIL }}\n  password $HEROKU_API_KEY\nmachine git.heroku.com\n  login ${{ secrets.HEROKU_EMAIL }}\n  password $HEROKU_API_KEY" > ~/.netrc

      - name: Deploy Backend Subdirectory to Heroku
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git || true
          git fetch heroku main
          git merge heroku/main --allow-unrelated-histories -m "Merge Heroku changes into backend"
          git subtree push --prefix backend heroku main || {
            echo "Subtree push failed, pulling changes from Heroku..."
            git pull heroku main
            echo "Pushing changes to Heroku after pull..."
            git subtree push --prefix backend heroku main
          }
