name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Deploy to Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat > ~/.netrc << EOF
          machine api.heroku.com
            login $HEROKU_LOGIN
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_LOGIN
            password $HEROKU_API_KEY
          EOF
          PR_NUMBER=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
          URI=https://api.github.com
          API_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          pr_resp=$(curl -s -H "${AUTH_HEADER}" -H "${API_HEADER}" \
                             "${URI}/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER")
          HEAD_BRANCH=$(echo "$pr_resp" | jq -r .head.ref)
          echo "HEAD_BRANCH is $HEAD_BRANCH"
          git push --force https://git.heroku.com/$HEROKU_APP_NAME.git \
            "origin/${HEAD_BRANCH}:master"
